# Generated by Django 5.0.2 on 2024-10-13 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_userotp_table_alter_users_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
            options={
                'db_table': 'sw_groups',
            },
        ),
        migrations.CreateModel(
            name='GroupMemebers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('group_memeber_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connections.groups')),
            ],
            options={
                'db_table': 'sw_group_members',
            },
        ),
    ]
