# Generated by Django 5.0.2 on 2024-10-14 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_groupconnections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupconnections',
            old_name='connection_id',
            new_name='group_connection_id',
        ),
    ]
