# Generated by Django 5.0.2 on 2024-10-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_rename_connection_id_groupconnections_group_connection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='money_owes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='groupconnections',
            name='money_owes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
