# Generated by Django 5.0.2 on 2024-10-14 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_userotp_table_alter_users_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('expense_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('money_owes', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('distribution_type', models.CharField(choices=[('PERCENTAGE', 'percentage'), ('EQUALLY', 'equally'), ('UNEQUALLY', 'unequally')], max_length=255, null=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expense1', to='user.users')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expense2', to='user.users')),
            ],
            options={
                'db_table': 'sw_expenses',
            },
        ),
    ]
