# Generated by Django 5.0.2 on 2024-10-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='total_money_owes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='distribution_type',
            field=models.CharField(choices=[('percentage', 'PERCENTAGE'), ('equally', 'EQUALLY'), ('unequally', 'UNEQUALLY')], max_length=255, null=True),
        ),
    ]
