# Generated by Django 5.0.2 on 2024-10-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expenses_total_money_owes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='money_owes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='total_money_owes',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
