# Generated by Django 5.0.2 on 2024-10-14 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_groupexpenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupexpenses',
            old_name='distribution_type_in_group',
            new_name='distribution_type',
        ),
        migrations.RenameField(
            model_name='groupexpenses',
            old_name='money_owes_in_group',
            new_name='money_owes',
        ),
        migrations.RenameField(
            model_name='groupexpenses',
            old_name='group_user1',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='groupexpenses',
            old_name='group_user2',
            new_name='user2',
        ),
    ]
