# Generated by Django 5.0.2 on 2024-10-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_rename_distribution_type_in_group_groupexpenses_distribution_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='groupexpenses',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
