# Generated by Django 5.0.2 on 2024-10-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expenses_description_groupexpenses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='total_money_owes',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
