# Generated by Django 5.0.2 on 2024-10-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_expenses_total_money_owes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupexpenses',
            name='total_money_owes',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
