BAD_REQUEST = "Some required fields missing"
WRONG_EMAIL = "No such email exists"
INCORRECT_PASSWORD = "please provide a correct password"
PASSWORD_LENGTH_SHOULD_BE_BETWEEN_8_TO_20 = "Your password length should be between 8 to 20."
PASSWORD_MUST_HAVE_ONE_NUMBER = "Your password must have at least 1 number"
PASSWORD_MUST_HAVE_ONE_SMALLERCASE_LETTER = "Your password must have at least 1 smallercase letter."
PASSWORD_MUST_HAVE_ONE_UPPERCASE_LETTER = "Your password must have at least 1 uppercase letter."
PASSWORD_MUST_HAVE_ONE_SPECIAL_CHARACTER = "Your password must have at least 1 special character ($, #, @, !, *)"
USER_REGISTERED_SUCCESSFULLY = "user Registered successfully"
USER_LOGGED_OUT_SUCCESSFULLY = "user logged out successfully"
USER_LOGGED_IN_SUCCESSFULLY = "user logged in successfully"
TOKEN_IS_EXPIRED = "token is expired"
USER_ALREADY_EXISTS = "user already exists"
SERIALIZER_IS_NOT_VALID = "serializer is not valid"
YOUR_PASSWORD_UPDATED_SUCCESSFULLY = "your password updated successfully"
NEW_PASSWORD_DOESNT_MATCH = "new password doesnt match"
OTP_SENT_SUCCESSFULLY = "OTP sent successfully"
OTP_DOESNT_MATCH = "OTP_doesnt_match"
OTP_EXPIRED = "OTP_expired"

USER_DOESNT_EXISTS = "user doesn't exists"
USER_IS_ALREADY_IN_THE_GROUP= "user is already in the group"
USER_ADDED_SUCCESSFULLY_IN_THE_GROUP = "user added successfully in the group"

GROUP_NOT_FOUND = "group not found"
GROUP_CREATED_SUCCESSFULLY = "Group created successfully"
GROUP_ALREADY_EXISTS="group already exists"
GROUP_FETCHED_SUCCESSSFULLY = "group fetched successfully"

YOU_ALREADY_JOINED_THE_GROUP = "you are already in the group"
CONNECTION_CREATED_SUCCESSFULLY = "connection created successfully"
CONNECTION_ALREADY_EXISTS = "connection already exists"
GROUPMEMBER_NOT_FOUND = "group member not found"
CONNECTION_NOT_FOUND = "connection not found"
GROUP_MEMBERS_LIST_REQUIRED = "group member list is required"
JOINED_GROUP_SUCCESSFULLY = "joined group successfully"
SUCCESSFULLY_FETCHED_CONNECTIONS = "successfully fetched all connections"

PERCENTAGE_REQUIRED = "percentage required"
INDIVIDUAL_EXPENSE_OF_BOTH_USER_IS_NECESSARY = "individual expense of both the user is necessary"
EXPENSE_ADDED_SUCCESSFULLY = "expense added successfully"
INCORRECT_USER_EXPENSES = "incorrect user expenses"
INCORRECT_USER_EXPENSES_PERCENTAGE = "incorrect user expenses_percentage"
EXPENSES_SETTLED_SUCCESSFULLY = "expenses settled successfully"

SUCCESSFULLY_FETCHED_TOTAL_OWED_MONEY = "successfully fetched the total owed money"