# Generated by Django 5.0.2 on 2024-10-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_users_userotp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userotp',
            table='sw_user_otp',
        ),
        migrations.AlterModelTable(
            name='users',
            table='sw_user',
        ),
    ]
